# CodeRabbit Configuration File
# CodeRabbit이 한국어로 리뷰를 제공하도록 설정

language: ko # 한국어로 설정

reviews:
  # 자동 리뷰 활성화
  auto_review:
    enabled: true
    drafts: false

  # 리뷰 프로필 및 설정
  profile: chill # assertive 대신 chill 모드 사용 (더 친절한 톤)
  request_changes_workflow: false
  high_level_summary: true
  poem: false # 시 생성 비활성화
  review_status: true
  collapse_walkthrough: false

  # 리뷰 대상에서 제외할 파일 패턴
  path_filters:
    - '!**/*.md'
    - '!**/package-lock.json'
    - '!**/pnpm-lock.yaml'
    - '!**/yarn.lock'
    - '!**/.next/**'
    - '!**/dist/**'
    - '!**/build/**'
    - '!**/node_modules/**'

chat:
  auto_reply: true

# 추가 설정
knowledge_base:
  enabled: true
  learnings:
    scope: auto
